# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
log_retention_days   = 14
name_prefix          = "cj-fastapi-ddd-dev"
reserved_concurrency = null
tags = {
  CostCenter  = "engineering"
  Environment = "dev"
  ManagedBy   = "terraform"
  Owner       = "cjgalvisc@unal.edu.co"
  Project     = "cj-fastapi-ddd"
}
