# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
name_prefix             = "cj-fastapi-ddd-dev"
recovery_window_in_days = 0
tags = {
  CostCenter  = "engineering"
  Environment = "dev"
  ManagedBy   = "terraform"
  Owner       = "cjgalvisc@unal.edu.co"
  Project     = "cj-fastapi-ddd"
}
