# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
aurora_max_capacity = 1
aurora_min_capacity = 0.5
deletion_protection = false
name_prefix         = "cj-fastapi-ddd-dev"
skip_final_snapshot = true
tags = {
  CostCenter  = "engineering"
  Environment = "dev"
  ManagedBy   = "terraform"
  Owner       = "cjgalvisc@unal.edu.co"
  Project     = "cj-fastapi-ddd"
}
